### ISSUE TITLE
Enable worker nodes to join cluster

### ISSUE THREAD

**Issue by kmd2kmd** [kmd2kmd/aws-cdk-eks#9]
1. Create a kubeconfig File
2. Apply the configuration

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: <ARN of instance role (not instance profile)>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
```

- https://docs.aws.amazon.com/eks/latest/userguide/getting-started-console.html
